"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from datetime import timedelta
import logging

from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env nằm cùng cấp với manage.py
load_dotenv(BASE_DIR / ".env")


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "null": {
            "level": "INFO",
            "class": "logging.NullHandler",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django.server": {
            "handlers": ["null"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ======================
# DJANGO CORE
# ======================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-cvbsxx-n%x%^40af+8^9-h+mbry(76cia18(sykids23d9=0b%",
)

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost,0.0.0.0,192.168.1.26,testserver",
    ).split(",")
    if host.strip()
]

# Nếu muốn giữ IP placeholder cũ
if "<IP-PC-TRONG-LAN>" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("<IP-PC-TRONG-LAN>")


# ======================
# APPS
# ======================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",

    "control",
    "authapp",
]


# ======================
# MIDDLEWARE
# ======================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "control.middleware.RobotActionEventMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "backend.urls"


# ======================
# TEMPLATES
# ======================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"


# ======================
# DATABASE
# ======================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": f"file:/{(BASE_DIR / 'app.sqlite3').as_posix()}?mode=rwc",
        "OPTIONS": {
            "init_command": "PRAGMA journal_mode=OFF; PRAGMA synchronous=OFF;",
        },
    }
}


# ======================
# PASSWORD VALIDATION
# ======================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ======================
# INTERNATIONALIZATION
# ======================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ======================
# STATIC
# ======================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ======================
# CORS / CSRF
# ======================

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "True").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8765,http://127.0.0.1:8765",
    ).split(",")
    if origin.strip()
]


# ======================
# CHANNELS
# ======================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# ======================
# DRF / JWT
# ======================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        seconds=int(os.getenv("JWT_ACCESS_TOKEN_LIFETIME", "3600"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        seconds=int(os.getenv("JWT_REFRESH_TOKEN_LIFETIME", "86400"))
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ======================
# ROBOT / DOGZILLA
# ======================

ROBOT_REG_SECRET = os.getenv("ROBOT_REG_SECRET", "dev-robot-secret")

ROBOT_SERVER_BASE_URL = os.getenv("ROBOT_SERVER_BASE_URL", "http://127.0.0.1:9000")
ROBOT_SERVER_TIMEOUT = int(os.getenv("ROBOT_SERVER_TIMEOUT", "5"))

ROBOT_IP = os.getenv("ROBOT_IP", "127.0.0.1")
ROBOT_PORT = os.getenv("ROBOT_PORT", "9000")
ROBOT_TIMEOUT = int(os.getenv("ROBOT_TIMEOUT", "5"))

MAP_SERVER_PORT = os.getenv("MAP_SERVER_PORT", "8080")

# Một số service đang đọc DOGZILLA_TIMEOUT / DOGZILLA_STREAM_TIMEOUT
DOGZILLA_TIMEOUT = int(os.getenv("DOGZILLA_TIMEOUT", os.getenv("ROBOT_TIMEOUT", "5")))
DOGZILLA_STREAM_TIMEOUT = int(os.getenv("DOGZILLA_STREAM_TIMEOUT", "30"))

LIDAR_RESET_DELAY_SECONDS = float(os.getenv("LIDAR_RESET_DELAY_SECONDS", "1.0"))


# ======================
# OPENROUTER LLM
# ======================

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "").strip()
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "openai/gpt-4.1-mini").strip()
LLM_MAX_ACTIONS = int(os.getenv("LLM_MAX_ACTIONS", "5"))
