from django.urls import path
from .views import (
    RobotListView,
    NetworkMetricsView,
    EvaluationMetricsView,
    ActionEventListView,
    SessionSummaryView,
    ConnectView,
    RobotRootInfoView,
    RobotHealthView,
    RobotFrameView,
    RobotTestPageView,
    RobotStatusView,
    FPVView,
    SpeedModeView,
    PaceModeView,
    MoveCommandView,
    PostureView,
    BehaviorView,
    LidarView,
    ResetLidarView,
    ZControlView,
    AttitudeControlView,
    BodyAdjustView,
    StabilizingModeView,
    GaitTypeView,
    PerformModeView,
    MarkTimeView,
    ResetRobotView,
    RawControlView,
    ControlStatusView,
    CameraProcessView,
    TextCommandView,
    QRStateView,
    QRPositionView,
    QRVideoFeedView,
    SlamStateView,
    SlamMapView,
    PointsView,
    DeletePointView,
    GoToPointView,
    GoToMarkerView,
    ManualGoalView,
    PatrolStartView,
    PatrolStopView,
    PatrolPauseView,
    PatrolResumeView,
    PatrolStatusView,
    PatrolHistoryView,
    QRMetricView,   
)



urlpatterns = [
    path("api/robots/<str:robot_id>/qr-metrics/", QRMetricView.as_view(), name="robot-qr-metrics"),
    path("api/robots/", RobotListView.as_view(), name="robots-list"),
    path("api/robots/<str:robot_id>/network/metrics/", NetworkMetricsView.as_view(), name="robot-network-metrics"),
    path("api/robots/<str:robot_id>/evaluation/metrics/", EvaluationMetricsView.as_view(), name="robot-evaluation-metrics"),
    path("api/robots/<str:robot_id>/events/", ActionEventListView.as_view(), name="robot-events"),
    path("api/robots/<str:robot_id>/session/summary/", SessionSummaryView.as_view(), name="robot-session-summary"),
    path("api/robots/<str:robot_id>/server/", RobotRootInfoView.as_view(), name="robot-server-root"),
    path("api/robots/<str:robot_id>/health/", RobotHealthView.as_view(), name="robot-health"),
    path("api/robots/<str:robot_id>/frame/", RobotFrameView.as_view(), name="robot-frame"),
    path("api/robots/<str:robot_id>/test/", RobotTestPageView.as_view(), name="robot-test-page"),
    path("api/robots/<str:robot_id>/connect/", ConnectView.as_view(), name="robot-connect"),
    path("api/robots/<str:robot_id>/status/", RobotStatusView.as_view(), name="robot-status"),
    path("api/robots/<str:robot_id>/control-status/", ControlStatusView.as_view(), name="robot-control-status"),
    path("api/robots/<str:robot_id>/fpv/", FPVView.as_view(), name="robot-fpv"),
    path("api/robots/<str:robot_id>/camera/", CameraProcessView.as_view(), name="robot-camera"),

    path("api/robots/<str:robot_id>/command/move/", MoveCommandView.as_view(), name="robot-move"),
    path("api/robots/<str:robot_id>/command/speed/", SpeedModeView.as_view(), name="robot-speed"),
    path("api/robots/<str:robot_id>/command/pace/", PaceModeView.as_view(), name="robot-pace"),
    path("api/robots/<str:robot_id>/command/z/", ZControlView.as_view(), name="robot-z-control"),
    path("api/robots/<str:robot_id>/command/attitude/", AttitudeControlView.as_view(), name="robot-attitude-control"),
    path("api/robots/<str:robot_id>/command/posture/", PostureView.as_view(), name="robot-posture"),
    path("api/robots/<str:robot_id>/command/behavior/", BehaviorView.as_view(), name="robot-behavior"),
    path("api/robots/<str:robot_id>/command/lidar/", LidarView.as_view(), name="robot-lidar"),
    path("api/robots/<str:robot_id>/command/lidar/reset/", ResetLidarView.as_view(), name="robot-lidar-reset"),
    path("api/robots/<str:robot_id>/command/body_adjust/", BodyAdjustView.as_view(), name="robot-body-adjust"),
    path("api/robots/<str:robot_id>/command/gait/", GaitTypeView.as_view(), name="robot-gait-type"),
    path("api/robots/<str:robot_id>/command/perform/", PerformModeView.as_view(), name="robot-perform"),
    path("api/robots/<str:robot_id>/command/mark-time/", MarkTimeView.as_view(), name="robot-mark-time"),
    path("api/robots/<str:robot_id>/command/reset/", ResetRobotView.as_view(), name="robot-reset"),
    path(
        "api/robots/<str:robot_id>/command/stabilizing_mode/",
        StabilizingModeView.as_view(),
        name="robot-stabilizing-mode",
    ),
    path("api/robots/<str:robot_id>/command/raw/", RawControlView.as_view(), name="robot-raw-control"),
    path("api/robots/<str:robot_id>/command/text/", TextCommandView.as_view(), name="robot-text-command"),

    path("api/robots/<str:robot_id>/qr/state/", QRStateView.as_view(), name="robot-qr-state"),
    path("api/robots/<str:robot_id>/qr/position/", QRPositionView.as_view(), name="robot-qr-position"),
    path("api/robots/<str:robot_id>/qr/video-feed/", QRVideoFeedView.as_view(), name="robot-qr-video-feed"),

    path("api/robots/<str:robot_id>/slam/state/", SlamStateView.as_view(), name="robot-slam-state"),
    path("api/robots/<str:robot_id>/slam/map.png", SlamMapView.as_view(), name="robot-slam-map"),

    path("api/robots/<str:robot_id>/points/", PointsView.as_view(), name="robot-points"),
    path("api/robots/<str:robot_id>/delete-point/", DeletePointView.as_view(), name="robot-delete-point"),
    path("api/robots/<str:robot_id>/go-to-point/", GoToPointView.as_view(), name="robot-go-to-point"),
    path("api/robots/<str:robot_id>/go-to-marker/", GoToMarkerView.as_view(), name="robot-go-to-marker"),
    path("api/robots/<str:robot_id>/manual-goal/", ManualGoalView.as_view(), name="robot-manual-goal"),

    path("api/robots/<str:robot_id>/patrol/start/", PatrolStartView.as_view(), name="robot-patrol-start"),
    path("api/robots/<str:robot_id>/patrol/stop/", PatrolStopView.as_view(), name="robot-patrol-stop"),
    path("api/robots/<str:robot_id>/patrol/pause/", PatrolPauseView.as_view(), name="robot-patrol-pause"),
    path("api/robots/<str:robot_id>/patrol/resume/", PatrolResumeView.as_view(), name="robot-patrol-resume"),
    path("api/robots/<str:robot_id>/patrol/status/", PatrolStatusView.as_view(), name="robot-patrol-status"),
    path("api/robots/<str:robot_id>/patrol/history/", PatrolHistoryView.as_view(), name="robot-patrol-history"),
]
