# Generated by Django 6.0.4 on 2026-04-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_plaintext',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
