# Generated by Django 6.0.4 on 2026-04-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvent',
            fields=[
                ('id', models.CharField(default='', max_length=32, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Info', max_length=16)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Active', 'Active')], default='Success', max_length=16)),
                ('action', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('detail', models.TextField(blank=True, default='')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='control.robot')),
            ],
        ),
    ]
