# Generated by Django 5.2.8 on 2026-04-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0002_actionevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("run_started_at", models.FloatField(db_index=True)),
                ("method", models.CharField(blank=True, default="", max_length=64)),
                ("route_id", models.CharField(blank=True, default="", max_length=128)),
                ("trial_id", models.CharField(blank=True, default="", max_length=128)),
                ("condition", models.CharField(blank=True, default="", max_length=128)),
                ("weighting_mode", models.CharField(blank=True, default="", max_length=64)),
                ("has_exact_localization", models.BooleanField(default=False)),
                ("has_exact_qr_ablation", models.BooleanField(default=False)),
                ("has_exact_navigation", models.BooleanField(default=False)),
                ("payload_mode", models.JSONField(blank=True, default=dict)),
                ("derived_metrics", models.JSONField(blank=True, default=dict)),
                ("paper_tables", models.JSONField(blank=True, default=dict)),
                ("raw_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_snapshots",
                        to="control.robot",
                    ),
                ),
            ],
        ),
    ]
