# Generated by Django 5.2.1 on 2026-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_patrolhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolhistory',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Tổng quãng đường di chuyển (m)', null=True),
        ),
        migrations.AlterField(
            model_name='actionevent',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
