# Generated by Django 5.2.1 on 2026-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_patrolhistory_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionevent',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
