# Generated by Django 5.2.14 on 2026-05-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_prune_metricsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversationMetric',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('input_text', models.TextField(blank=True, default='')),
                ('robot_addr', models.CharField(blank=True, default='', max_length=256)),
                ('planner_source', models.CharField(blank=True, default='', max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('reply_text', models.TextField(blank=True, default='')),
                ('llm_error', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('results_json', models.JSONField(blank=True, default=list)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversation_metrics', to='control.robot')),
            ],
            options={
                'db_table': 'voice_conversation_metric',
                'ordering': ['-created_at'],
            },
        ),
    ]
